### ISSUE TITLE
UnrecognizedFlagError: Unknown command line flag 'f'

### ISSUE THREAD

**Issue by setsometso** [coMindOrg/federated-averaging-tutorials#1]
Hi there, running the notebooks (distributed and federated notebook) you get the following error:

UnrecognizedFlagError: Unknown command line flag 'f'

**Comment by ceballosiker** [comment]
Hi! Thank you for trying the tutorials!

The distributed and federated notebooks can't be run, you actually need to download the code and run three different shells. The reason being that we use three separate processes for the different tasks.
