### ISSUE TITLE
Federated Learning Linear regression

### ISSUE THREAD

**Issue by codarm** [coMindOrg/federated-averaging-tutorials#2]

**Comment by edumugi** [comment]
Could you give us please some more information about what you need?

**Comment by codarm** [comment]
I am new to tensorflow and federated learning. I am looking forward to using the socket programming tutorial for some time series data forecasting at a federated level. Most of the tutorials on federated learning revolve around image datasets but nothing around simple Linear Regression models. Could You help me use the same code of socket -federated learning for a time series dataset. It would be good if you could send the code for any of the federated models with linear regression training on time series data.

**Comment by ceballosiker** [comment]
The image classification task solved in these tutorials is just an example.

Implementing a linear regression model is exactly the same. Just define the graph and add the federated hook to your training session.

If you are asking how to implement simple linear regression models in tensorflow, the official page has several [tutorials](https://www.tensorflow.org/tutorials/keras/basic_regression) that are perfect for beginners.
