### ISSUE TITLE
Run on multiple machines

### ISSUE THREAD

**Issue by MahboobehJannesari** [coMindOrg/federated-averaging-tutorials#7]
I run basic_distributed_classifier.py on 3 machines, there are 2 workers and one ps, when I run code is waiting in worker, Could you please help me in this regards?
FYI, when i run on one worker and one ps, there is no problem.

I uses 
python 3.6
ubuntu 18.04
tensorflow 2.2

**Comment by jalbertoroman** [comment]
Hi Mahboubeh, this example works with TF 1.3. In a few weeks we will be releasing an updated version for TF 2.2. For what application are you using the code? If we can help lets us know.

**Comment by MahboobehJannesari** [comment]
Hello,

I use for research on healthcare dataset,

I changed code and make it compatible for tensorflow2.2, but for multiple
machines, it doesn't work,

After running on more 2 workers,  the code waiting on workers.


I do appreciate if you can help me.

Best regards
Mahboubeh

**Comment by jalbertoroman** [comment]
Or code base has change a lot and the approach to FL. Or new version will be out in a few weeks, I'll will keep you posted. 

Thanks,
Alberto.
