### ISSUE TITLE
While executing advanced_classifier.py its displaying an error for the cifar10.so i checked this link:Check this script to see how to generate CIFAR-10 TFRecords. But its displaying file not found.please help me regarding this

### ISSUE THREAD

**Issue by aiswariya-cse** [coMindOrg/federated-averaging-tutorials#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aiswariya-cse** [comment]
please help me regarding this .i am not able to move forward

**Comment by jalbertoroman** [comment]
This project is not maintained. Check out www.acuratio.com
